apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftw-domain-manager
spec:
  replicas: 2
  serviceName: ftw-domain-manager
  selector:
    matchLabels:
      run: ftw-domain-manager
  template:
    metadata:
      labels:
        run: ftw-domain-manager
    spec:
      containers:
      - name: ftw-domain-manager
        image: registry.gitlab.com/freethewumpus/domain_manager
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            port: 8000
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            port: 8000
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: CLUSTER_ID
          value: b9a8389f-646a-47ba-85ec-ec2de6866e75
        - name: CLUSTER_CNAME
          value: "freethewump.us"
        - name: DIGITALOCEAN_TOKEN
          valueFrom:
            secretKeyRef:
              name: ftw-domain-manager
              key: digitalocean_token
      imagePullSecrets:
      - name: gitlab
